services:
  backend:
    build: ./backend
    container_name: rewards_backend
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy-network
      - database-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: rewards_frontend
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
  database-network:
    external: true